apiVersion: v1
kind: Service
metadata:
  name: logscope-api
  namespace: logscope
spec:
  selector:
    app: logscope-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
